### ISSUE TITLE
Yahtzee wildcard does not allow score of 25 for full house

### ISSUE THREAD

**Issue by sturgman** [kburton/elm-yahtzee#1]
Hey! 

Love the game and implementation. Perfectly done. I had a game were I had a second Yahtzee and a blank full house space. I couldn't claim the 25 points for the full house. Pretty certain it is a bug. Unfortunately, I accidentally quit the game before I could screen shot.

**Comment by kburton** [comment]
Hey. Glad to hear you're enjoying the game.

You can only use a wildcard if the corresponding top section has already been scored. For instance, if you roll five twos and you haven't yet filled in the twos section at the top, you won't be able to use the wildcard. Let me know if that sounds like the situation you were in.

**Comment by sturgman** [comment]
That must have been it. If I see it again I'll confirm.
